In [4]:
import numpy as np
import numpy.linalg as la

In [5]:
A = np.matrix([[5, 6], [2, 3], [4, 5], [6, 7]])
n, m = A.shape


In [10]:
At = A.transpose()
print At

[[5 2 4 6]
 [6 3 5 7]]


In [17]:
eigval, U=la.eig(np.matmul(A, At))
eigval2, V=la.eig(np.matmul(At, A))

In [18]:
D=np.zeros((n, m))
np.fill_diagonal(D, (np.sort(eigval)[::-1])**(1/2))

In [19]:
print("A=U*D*V(transpose) = ")
print U*D*V.transpose();

A=U*D*V(transpose) = 
[[ 0.36579017 -0.42483322]
 [ 0.75196564  0.51295137]
 [ 0.49451533 -0.11223836]
 [ 0.23706502 -0.73742808]]
